---
- name: Hostname configuration
  block:

  - name: Set hostname
    hostname:
      name: "{{ ansible_hostname }}.{{ freeipa_domain }}"
      use: "systemd"

  - name: Chattr /etc/hosts
    file:
      path: /etc/hosts
      attributes: '-i'

  - name: Rewrite /etc/hosts
    replace:
      path: /etc/hosts
      after: '.'
      regexp: '^(.+)$'
      replace: '{{ ansible_hostname }}.{{ freeipa_domain }}'

  when: ansible_facts.virtualization_type != "docker"

- name: Upgrade ubuntu hosts
  apt:
    upgrade: full
    update_cache: yes
  when: ansible_facts.distribution == 'Ubuntu'

- name: Update fedora hosts
  yum:
    update_cache: true
    update_only: true
  when: ansible_facts.distribution == 'Fedora'

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ packages }}"