---
- name: Upgrade ubuntu hosts
  apt:
    only_upgrade: true
  when: ansible_facts.distribution == 'Ubuntu'

- name: Update fedora hosts
  yum:
    update_only: true
  when: ansible_facts.distribution == 'Fedora'

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ packages }}"
