---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    hostname: host1
    dockerfile: ../common/Dockerfile.j2
    image: ubuntu:22.04
    pre_build_image: false
  - name: fedora
    hostname: host2
    dockerfile: ../common/Dockerfile.j2
    image: fedora:38
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
